# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a626f3abb05af76db49f8d377ed4cf94941f417a672b811541e63e3ab6d8007c8edbbc49aadb5d010924997ebd1fc9169a8c7a8b8d2fd5a4fc4d60d2c534050a

test:
  secret_key_base: c75dd6935c2c9b4170f6454147e7758c483cffd0a40ba1e8165655c0e2ebbd72cc7b151c79512aa4ee9f9f3607ee3321adf8bf5ab676ded7dfd1589be5ae18ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
